language: rust
sudo: false

cache: cargo

before_script:
  - export PATH=$HOME/.cargo/bin:$PATH
  - rustup component add rustfmt-preview

script:
  - cargo fmt -- --check
  - cargo build
  - cargo test

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
